name: env_hackanexoplanet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab=3.5.2
  - ipywidgets=7.6.5
  - ipympl=0.9.2
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - nbgitpuller
  - emcee
  - h5py
  - ellc